name: linter

on:
  - push
  - pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: 
          pip install poetry
          make install
          poetry add --dev flake8
      - name: run linter
        run: 
          make lint
